# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 7
  labels:
    k8s-app: local-finder-backend
  name: local-finder-backend
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: local-finder-backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: local-finder-backend
      name: local-finder-backend
    spec:
      volumes:
        - name: env
          configMap:
            name: local-finder-backend
            items: 
              - key: env
                path: .env
      containers:
      - image: ghcr.io/smart-city-sose-2022/local-finder-backend:main
        imagePullPolicy: Always
        name: local-finder-backend
        volumeMounts:
          - name: env
            readOnly: true
            mountPath: /app/.env
            subPath: .env
        resources: {}
        securityContext:
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: github-docker-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2022-05-09T10:34:48Z"
    lastUpdateTime: "2022-05-09T10:34:48Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-05-09T09:53:14Z"
    lastUpdateTime: "2022-05-28T17:11:57Z"
    message: ReplicaSet "local-finder-backend-6dd5999646" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 7
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
