"""empty message

Revision ID: 095b94f66b77
Revises: 0745d0e35953
Create Date: 2022-05-23 18:30:33.675416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '095b94f66b77'
down_revision = '0745d0e35953'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lokal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lokal')
    # ### end Alembic commands ###
