"""empty message

Revision ID: 4b7f02fe54e9
Revises: 095b94f66b77
Create Date: 2022-05-31 09:36:07.235968

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4b7f02fe54e9'
down_revision = '095b94f66b77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    op.add_column('lokal', sa.Column('ownedBy', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lokal', 'account', ['ownedBy'], ['id'])
    op.add_column('reservation', sa.Column('reservedBy', sa.Integer(), nullable=True))
    op.add_column('reservation', sa.Column('reservedLocal', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reservation', 'account', ['reservedBy'], ['id'])
    op.create_foreign_key(None, 'reservation', 'lokal', ['reservedLocal'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reservation', type_='foreignkey')
    op.drop_constraint(None, 'reservation', type_='foreignkey')
    op.drop_column('reservation', 'reservedLocal')
    op.drop_column('reservation', 'reservedBy')
    op.drop_constraint(None, 'lokal', type_='foreignkey')
    op.drop_column('lokal', 'ownedBy')
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('completed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='test_pkey')
    )
    # ### end Alembic commands ###
