"""empty message

Revision ID: 6d9aae4fcb9d
Revises: 72bb3c368f28
Create Date: 2022-05-31 14:53:27.715271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d9aae4fcb9d'
down_revision = '72bb3c368f28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lokal', sa.Column('name', sa.String(), nullable=True))
    op.add_column('lokal', sa.Column('owner', sa.Integer(), nullable=True))
    op.drop_constraint('lokal_ownedBy_fkey', 'lokal', type_='foreignkey')
    op.create_foreign_key(None, 'lokal', 'account', ['owner'], ['id'])
    op.drop_column('lokal', 'ownedBy')
    op.drop_column('reservation', 'personNumber')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('personNumber', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('lokal', sa.Column('ownedBy', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'lokal', type_='foreignkey')
    op.create_foreign_key('lokal_ownedBy_fkey', 'lokal', 'account', ['ownedBy'], ['id'])
    op.drop_column('lokal', 'owner')
    op.drop_column('lokal', 'name')
    # ### end Alembic commands ###
