"""empty message

Revision ID: 72bb3c368f28
Revises: 4b7f02fe54e9
Create Date: 2022-05-31 11:08:13.496883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72bb3c368f28'
down_revision = '4b7f02fe54e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('street', sa.String(), nullable=True))
    op.add_column('account', sa.Column('plz', sa.String(length=5), nullable=True))
    op.drop_column('account', 'age')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('account', 'plz')
    op.drop_column('account', 'street')
    # ### end Alembic commands ###
