"""empty message

Revision ID: 9c71552acfd0
Revises: ac098af48b71
Create Date: 2022-06-19 17:38:28.705269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c71552acfd0'
down_revision = 'ac098af48b71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lokaltype',
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('type')
    )
    op.create_table('typeTable',
    sa.Column('lokal_id', sa.Integer(), nullable=True),
    sa.Column('lokal_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['lokal_id'], ['lokal.id'], ),
    sa.ForeignKeyConstraint(['lokal_type'], ['lokaltype.type'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('typeTable')
    op.drop_table('lokaltype')
    # ### end Alembic commands ###
