"""empty message

Revision ID: faf26ff5042c
Revises: ac098af48b71
Create Date: 2022-06-20 13:13:56.030568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faf26ff5042c'
down_revision = 'ac098af48b71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lokaltype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('typeTable',
    sa.Column('lokal_id', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lokal_id'], ['lokal.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['lokaltype.id'], )
    )
    op.add_column('lokal', sa.Column('address', sa.String(), nullable=True))
    op.add_column('lokal', sa.Column('plz', sa.String(), nullable=True))
    op.add_column('lokal', sa.Column('city', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lokal', 'city')
    op.drop_column('lokal', 'plz')
    op.drop_column('lokal', 'address')
    op.drop_table('typeTable')
    op.drop_table('lokaltype')
    # ### end Alembic commands ###
